version: '3'
services:
  app:
    container_name: dockernodemongo
    restart: always
    build: .
    ports:
      - '1025:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo

